help: ## SHOW THIS HELP: OPTIONs/ARGUMENTs to pass with "make"
				@fgrep -h "##" $(MAKEFILE_LIST) | grep -v fgrep

catalogue:  ## USE THIS OPTION TO INSTALL "catalogue" service
				@bash catalogue.sh
cart:			## USE THIS OPTION TO INSTALL "cart" service
				@bash cart.sh
mongodb:	## USE THIS OPTION TO INSTALL "mongodb" service
				@bash component/mongodb.sh
mysql:		## USE THIS OPTION TO INSTALL "mysql" service
				@bash component/mysql.sh
redis:		## USE THIS OPTION TO INSTALL "redis" service
				@bash component/redis.sh
user:			## USE THIS OPTION TO INSTALL "user" service
				@bash component/user.sh
shipping:	## USE THIS OPTION TO INSTALL "shipping" service
				@bash component/shipping.sh
payment:	## USE THIS OPTION TO INSTALL "payment" service
				@bash component/payment.sh
rabbitmq:	## USE THIS OPTION TO INSTALL "rabbitmq" service
				@bash component/rabbitmq.sh
frontend:	## USE THIS OPTION TO INSTALL "frontend" service
				@bash component/frontend.sh
